[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]
gas_reports = ["TempestHook", "TickObserverHarness", "VolEngineHarness"]

[profile.default.fuzz]
runs = 256
